### ISSUE TITLE
Potential EVGA issue

### ISSUE THREAD

**Issue by sschwartz0** [nehalist/ilovertx3000#1]
I don't know if this will work for EVGA. Here's an in stock item. It doesn't look like it has a .message-information element. Looking for the add to cart button is probably safer.

![image](https://user-images.githubusercontent.com/21964998/93720025-4ce5eb00-fb3b-11ea-9d10-6393ebbdd903.png)

**Comment by AdmiralGama** [comment]
The bot is made for RTX 3000 series cards

**Comment by wazerstar** [comment]
> 
> 
> The bot is made for RTX 3000 series cards

You clearly dont think about of the box, of course you pick another item that is available to see what information you can harvest for this script
